### ISSUE TITLE
Feature Request V2: 5V auf Pin-Leiste herausführen

### ISSUE THREAD

**Issue by NemoN** [JanGoe/esp8266-wifi-relay#12]

**Comment by JanGoe** [comment]
![spannungs-punkte](https://cloud.githubusercontent.com/assets/16207460/11811022/fe08742c-a332-11e5-9c84-0e4b4725d58e.jpg)

an den roten punkte kann man 5v "abgreifen"
an den gelben punkten 3,3v

**Comment by JanGoe** [comment]
in der nächsten pcb version 

wird es einen 3,3v pin und einen 5v pin geben
