### ISSUE TITLE
Schematik

### ISSUE THREAD

**Issue by Dietmar-Franken** [JanGoe/esp8266-wifi-relay#14]
Schön wäre es wenn hier wie bei anderen Projekten die Schematik und die Bauteileliste eingepflegt werden könnte,dann wäre es perfekt.

**Comment by IVI053** [comment]
Würde ich auch absolut unterstützen.

**Comment by NemoN** [comment]
https://github.com/JanGoe/esp8266-wifi-relay/pull/29
