### ISSUE TITLE
Statische IP

### ISSUE THREAD

**Issue by xCite1986** [JanGoe/esp8266-wifi-relay#24]
um eine Statische IP einzubinden, hab ich in die 5. Zeile in der init.lua ergänzt

![2016-01-27_23-52-00](https://cloud.githubusercontent.com/assets/10913090/12631306/fee0e7ea-c550-11e5-9dc5-782433af984a.png)

edit: WLAN SSID und WLAN-Kennwort müssen vor Ergänzung der Zeile konfiguriert werden.

**Comment by JanGoe** [comment]
Hallo,

Danke dafür allerdings würde dies einen kleinen fehler verurschen das es dazu kommen könnte das der TCP server nicht startet

die prüfung ob die ip nicht null ist wird "übersprungen" und somit startet direkt die aktor.lua und der tcp server und das obwohl wlan evtl noch nicht richtig verbunden ist

ich lasse mir hierfür eine lösung einfallen

**Comment by xCite1986** [comment]
keine Ursache.. oh. okay.. also sollten hierfür zwingend die WLAN-Einstellungen stimmen.

mein Schrottmodem kann nämlich keine IP´s an MAC-Adressen zuweisen.

Vielleicht macht die Integration einer Config-html nach der erstmaligen WLAN-Konfiguration sinn um diverse Variablen zu setzen (Verriegelung, low/high invertiert, Wlan-Settings, DHCP/StaticIP, DHT ein/aus... usw)

**Comment by JanGoe** [comment]
das mit der config.html nehme ich mal auf und schaue was ich machen kann

**Comment by kellermaaan** [comment]
Hab mal ne Frage, ist es möglich diesen Befehl: `php tcp.php 192.168.0.62 2x4x1` statt der IP mit dem Hostname zu nutzen? Wenn nicht wie sieht es denn mit der Einstellung der statischen IP aus? Wäre sehr hilfreich wenn man das vielleicht einstellen könnte...

**Comment by xCite1986** [comment]
Ich hab das ganze mit der ESPEasy und MQTT gelöst, reconnect funktioniert super, ip's laufen dennoch auf DHCP und das Modul erhält dann quasi einen Namen zum schalten  wie /switch_az/gpio/2 und zur statusübermittlung /switch_az/Switch_1/Switch

Im pimatic-forum ist alles dokumentiert

https://forum.pimatic.org/topic/1257/wifi-switch-to-integrate-in-wall/42#

LG alex

**Comment by xCite1986** [comment]
Ich hab das ganze mit der ESPEasy und MQTT gelöst, reconnect funktioniert super, ip's laufen dennoch auf DHCP und das Modul erhält dann quasi einen Namen zum schalten  wie /switch_az/gpio/2 und zur statusübermittlung /switch_az/Switch_1/Switch

Im pimatic-forum ist alles dokumentiert

https://forum.pimatic.org/topic/1257/wifi-switch-to-integrate-in-wall/42#

LG alex

**Comment by xCite1986** [comment]
Ich hab das ganze mit der ESPEasy und MQTT gelöst, reconnect funktioniert super, ip's laufen dennoch auf DHCP und das Modul erhält dann quasi einen Namen zum schalten  wie /switch_az/gpio/2 und zur statusübermittlung /switch_az/Switch_1/Switch

Im pimatic-forum ist alles dokumentiert

https://forum.pimatic.org/topic/1257/wifi-switch-to-integrate-in-wall/42#

LG alex

**Comment by kellermaaan** [comment]
Ich habe es mal getestet. Wenn man statt der IP den Hostname in den Befehl einfügt müsste es auch funktionieren. Hat zumindest bei mir so geklappt!

**Comment by xCite1986** [comment]
Bei mir hat der reconnect des moduls ins wlan nach einem routerreset leider nicht funktioniert...

**Comment by kellermaaan** [comment]
Hallo nochmal, ich wollte nochmal nachfragen, ob es nicht eine andere Möglichkeit gibt eine statische IP oder MQTT etc. einzustellen??? Das wäre nämlich echt super!

**Comment by JanGoe** [comment]
Hallo,

Welche probleme hast du denn das board zu steuern ?

was @xCite1986  schreibt in sachen MQTT über ESPEays ist sichher eine gute methode, hier kann man auch alles bequem über den Browser einstellen und braucht in lua dateien keine änderungen mehr vor zu nehmen


mit folgenden befehl : wifi.sta.setip({ip="192.168.0.126",netmask="255.255.255.0",gateway="192.168.0.1"})

kannst du dem esp aber auch eine feste ip geben

**Comment by xCite1986** [comment]
@kellermaaan 

Ich denke dass aktuell Softwareseitig ESPEasy am flexibelsten und angenehmsten zu bedienen ist.

in der config kannst du via Webinterface statische IP`s vergeben, MQTT konfigurieren, deine angeschlossenen Bauteile an den restlichen GPIO`s verwalten, interne rules anlegen etc...

http://www.youscreen.de/fptulhwcd24.jpg
http://www.youscreen.de/gfqiuvtyg40.jpg

Wie Jan oben schon erwähnt hat, funktioniert nach Verbindungsabriss kein reconnect.
Wenn du willst kann ich dir morgen step-by-step Support im Pimatic-Chat anbieten, 

LG Alex

**Comment by kellermaaan** [comment]
Erstmal danke für eure Hilfe aber momentan funktioniert es ganz gut. Aktuell spreche ich das Board über den Hostnamen an und reboote das Board nachts immer so gegen 2 Uhr. Nach einer gewissen Zeit ist das Board immer hängen geblieben... Das passiert nach dem rebooten bis jetzt nicht mehr.
Das mit "wifi.sta.setip({ip="192.168.0.126",netmask="255.255.255.0",gateway="192.168.0.1"})" habe ich auch schon versucht aber damit ist der TCP Server, wie in einem vorherigen Beitrag schon erwähnt, nicht gestartet.

**Comment by xCite1986** [comment]
gelöst, kommuniziere nun via mqtt mit dem board... aber nachwievor sind die boards im einsatz.. gute Arbeit.. respekt
