### ISSUE TITLE
Firmware im GIT korrupt?

### ISSUE THREAD

**Issue by tkoeberl** [JanGoe/esp8266-wifi-relay#43]
ich habe  meine ESP mit der Firmware aus dem GIT geflasht. Flashen funktionierte aber es war unmöglich eine kommunikation (schmierzeichen) per ttl usb aufzubauen, daher habe ich selbst eine Firmware bauen lassen.
Kann es sein das die GIT Firmware korrupt ist?

**Comment by JanGoe** [comment]
Also ich nutze diese aus Github auch, evtl solltest du sie mal neu runterladen ?

**Comment by tkoeberl** [comment]
Habe ich schon einige Male. Ich habe mir auch mal ein neues USBTTL bestellt. evtl liegt es auch daran.
