### ISSUE TITLE
GPIO2

### ISSUE THREAD

**Issue by xboxpro1** [JanGoe/esp8266-wifi-relay#54]
Hallo, laut Quellen im Internet muss GPIO2 HIGH sein beim booten. Laut Plan steuert GPIO2 über den FET aber Relais 1.  Ist der Plan oder sind die Quellen nicht korrekt?

**Comment by JanGoe** [comment]
GPIO2 hat beim starten immer wieder "komische" zustände so das es hierzu zu problemen kommen kann, zur zeit wird gpio2 für das Relais1 genutzt 

für v3 ist geplant GPIO2 gegen einen anderen zu tauschen

**Comment by xboxpro1** [comment]
OK, Danke.. Werde dann GPIO2 tauschen, wenn das Teil bei mir ist. Habe eines über eBay erstanden "xcancer777". Habe vor das hier zu verwenden..
<https://bitbucket.org/xoseperez/espurna>
Sollte mit Modifikationen der Ports funktionieren.

**Comment by NemoN** [comment]
Bei der V2 habe ich bei einem Board GPIO 2 und 13 getauscht:

Gelb = Leiterbahn durchtrennen
Grün = Verbinden ;-)

![relay_gpio2_13](https://cloud.githubusercontent.com/assets/2212175/20919058/39d32c42-bb9a-11e6-8fe6-51e402166f5a.jpg)

**Comment by xboxpro1** [comment]
Perfekt, danke. Ich würde noch GPIO2 auf HIGH legen.

**Comment by xboxpro1** [comment]
Habe hier ein Schaltbild für die korrekte GPIO Beschaltung.

![scheme-full](https://cloud.githubusercontent.com/assets/554227/21047371/d35b8898-be09-11e6-905e-b4164010c0c4.jpg)
